server:
  port: 8081
  servlet:
    context-path: /boot

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.2.201:32265/portal_dev?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: dldp_dev
    password: dldp@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
#    # 多数据源
#    dynamic:
#      primary: master # 设置默认数据源
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/master_db
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        slave1:
#          url: jdbc:mysql://localhost:3306/slave1_db
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        slave2:
#          url: jdbc:postgresql://localhost:5432/slave2_db
#          username: postgres
#          password: 123456
#          driver-class-name: org.postgresql.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
    - classpath*:mapper/*/*Mapper.xml
  executor-type: reuse

logging:
  config: classpath:logback.xml

sftp:
  host: 172.31.1.14
  port: 22
  hostname: scwdd
  password: scwdd@123
  path: /data/scwdd/pwyfile
  timeout: 30000


# SpringDoc OpenAPI 核心配置
springdoc:
  # Swagger UI 页面配置
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 访问路径（自定义，如：http://ip:port/上下文/swagger-ui.html）
    tags-sorter: alpha      # 接口标签（Tag）排序：alpha=字母序，method=定义顺序
    operations-sorter: alpha # 同标签下接口排序：alpha=路径字母序，method=HTTP方法序（GET→POST）
  # API 文档数据接口（Swagger UI 数据源，返回 JSON）
  api-docs:
    enable: true
    path: /v3/api-docs  # 文档数据路径（如：http://ip:port/上下文/v3/api-docs）
  # 接口分组配置（按包/路径筛选接口，避免无关接口混入文档）
  group-configs:
    - group: default          # 分组名称（Swagger UI 顶部可切换，默认一个分组）
      paths-to-match: /**     # 匹配所有路径的接口（可缩小范围，如：/personInfo/**）
      packages-to-scan: com.example.boot.controller # 扫描的控制器包（只解析该包下的接口）



# Knife4j 配置

knife4j:
  enable: true
  setting:
    # 显示接口统计信息
    showRequestParams: true
    showResponseParams: true
    # 分组配置
    group-config:
      - name: 默认分组
        paths: /.*$

